Add ability to get cables from CDP for Cisco IOS and NXOS
nautobot/nautobot-app-device-onboarding pull request #202
Opened 2024-07-11 20:38 UTC by scetron

Add ability to collect cables for Cisco IOS, NXOS, and JunOS.

Fixed some small documentation and comment typos. 

Implements/Fixes #201

2024-07-11 20:51 UTC, jeffkala reviewed
Can you update the jsonschema too?

2024-07-11 20:51 UTC, jeffkala commented on nautobot_device_onboarding/tests/test_formatter.py
> +        self.assertFalse(self.host.defaults.data.get("sync_cablesß"))
```suggestion
        self.assertFalse(self.host.defaults.data.get("sync_cables"))
```

2024-07-16 20:57 UTC, jeffkala approved these changes
Looks good to me, mind looking as well @Dav-C ?

2024-07-16 21:56 UTC, Dav-C commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> +                network_vlan.model_flags = DiffSyncModelFlags.SKIP_UNMATCHED_SRC
I think this will result in the deletion of VLANs from Nautobot. We can never be sure ALL of the available objects are loaded from the source as any subset of devices can be synced, so objects generally should not be deleted from Nautobot. There are some exceptions like IPAddress to Interface, we know that is localized to the device being synced. Won't skipping the unmatched source also prevent the creation of new VLANs?

2024-07-16 21:57 UTC, Dav-C commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> -                network_ip_address.model_flags = DiffSyncModelFlags.SKIP_UNMATCHED_DST
I believe this will result in the attempted deletion of all IP Address from Nautobot not loaded from the source.

2024-07-16 22:13 UTC, Dav-C commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> +        for device in self.job.devices_to_load:
Is it possible for a any of these objects not to exist? if so anything with ".name" will throw an exception. This scenario is pretty common so I would recommend a try/except with some error logging to be sure a missing value doesn't crash the sync.

2024-07-16 22:37 UTC, Dav-C commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> +            for neighbor_data in device_data["cables"]:
This is probably a good place to use self._handle_general_load_exception() The schema check catches most stuff now, but this is a catch of last resort for missing keys to prevent the job from crashing.

2024-07-17 13:35 UTC, scetron commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> +                network_vlan.model_flags = DiffSyncModelFlags.SKIP_UNMATCHED_SRC
This may have been a mistake on my part. I will revert this change.

2024-07-17 13:35 UTC, scetron commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> -                network_ip_address.model_flags = DiffSyncModelFlags.SKIP_UNMATCHED_DST
This may have been a mistake on my part. I will revert this change.

2024-07-17 16:58 UTC, susanhooks commented on nautobot_device_onboarding/command_mappers/cisco_ios.yml
> +  cables:
Could you add cables to the XE command mapper as well please?

2024-07-17 20:10 UTC, susanhooks requested changes
We need error handling if someone tries to run the "sync cables" and that platform is not yet supported. Potentially [here](https://github.com/nautobot/nautobot-app-device-onboarding/blob/4cfbca05061f10c7e464a92bc38bc762ced2e09a/nautobot_device_onboarding/nornir_plays/command_getter.py#L95). 
Fail the job and let them know why. 

Alternatively, don't fail the job but pass back the expected data structure with the key of "cables" empty, but give a warning. Might also want to include this in the tool tip or description on the job.

2024-07-18 16:12 UTC, scetron commented on nautobot_device_onboarding/command_mappers/cisco_ios.yml
> +  cables:
Yes.

2024-07-18 16:13 UTC, scetron commented on nautobot_device_onboarding/command_mappers/cisco_ios.yml
> +        jpath: "[*].{local_interface:local_interface, remote_interface:neighbor_interface, remote_device:neighbor_name}"
This is interesting because I think some customer include the FQDN in the device name in Nautobot as well as the device's hostname?

2024-07-18 16:14 UTC, scetron commented on nautobot_device_onboarding/jobs.py
> +    sync_cables = BooleanVar(default=False, description="Sync cables between interfaces via a LLDP or CDP.")
From what I see in NTC templates, LLDP neighbor templates are available and have similar or same fields available. While not supported in the platforms where cables are added, they could could override this with another yaml and change it to LLDP.

2024-07-19 16:05 UTC, scetron commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> +        for device in self.job.devices_to_load:
I think that the device name is the only thing that is not required in Nautobot, so I will do a check for that prior to attempting the load and utilize this.

2024-07-19 16:35 UTC, scetron commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> +                self.job.logger.debug(f"Cable Data: {device_data['cables']}")
I have added some checks for the data type and none

2024-07-19 16:41 UTC, susanhooks commented on nautobot_device_onboarding/command_mappers/cisco_ios.yml
> +        jpath: "[*].{local_interface:local_interface, remote_interface:neighbor_interface, remote_device:neighbor_name}"
True. Trying to get away from plugin config for this kind of stuff, but maybe that's the only way. @jeffkala ?

2024-07-19 20:19 UTC, Dav-C commented on nautobot_device_onboarding/diffsync/adapters/sync_network_data_adapters.py
> +                    self._handle_general_load_exception(
Thank you for adding this. I should be more explicit about the required arguments, but handle_general_load_exception is expecting the actual error object itself as in the function `.args` is called on the error. You should be able to pass the error itself and add the message to it as an argument however.

2024-07-31 01:37 UTC, scetron commented
> We need error handling if someone tries to run the "sync cables" and that platform is not yet supported. Potentially [here](https://github.com/nautobot/nautobot-app-device-onboarding/blob/4cfbca05061f10c7e464a92bc38bc762ced2e09a/nautobot_device_onboarding/nornir_plays/command_getter.py#L95). Fail the job and let them know why.
> 
> Alternatively, don't fail the job but pass back the expected data structure with the key of "cables" empty, but give a warning. Might also want to include this in the tool tip or description on the job.

For now, we're throwing and handling the error, but proceeding with the rest as there seems to be an issue with stopping the whole job at that point! Please have a look :)

2024-07-31 21:24 UTC, susanhooks commented
> > We need error handling if someone tries to run the "sync cables" and that platform is not yet supported. Potentially [here](https://github.com/nautobot/nautobot-app-device-onboarding/blob/4cfbca05061f10c7e464a92bc38bc762ced2e09a/nautobot_device_onboarding/nornir_plays/command_getter.py#L95). Fail the job and let them know why.
> > Alternatively, don't fail the job but pass back the expected data structure with the key of "cables" empty, but give a warning. Might also want to include this in the tool tip or description on the job.
> 
> For now, we're throwing and handling the error, but proceeding with the rest as there seems to be an issue with stopping the whole job at that point! Please have a look :)

I don't think this is working. In my test, I'm not getting the error message. I think this is due to mishandling in the processor of subtask failure. It's not a total no-go for the feature, as it still exits somewhat gracefully.

2024-07-31 21:36 UTC, susanhooks approved these changes

2024-08-01 00:53 UTC, merged