Add FQDN support for device onboarding
nautobot/nautobot-app-device-onboarding pull request #251
Opened 2024-10-04 22:15 UTC by susanhooks

Added support to use FQDN to onboard devices in _validate_ip_addresses function, formatting. 
Updated job description. 
Addresses feature request #241

2024-10-10 14:21 UTC, jeffkala reviewed
Looks good.  I'm a bit confused by some of the formatting changes.  Almost like ruff isn't using the correct profile or something?

2024-10-10 14:21 UTC, jeffkala commented on nautobot_device_onboarding/diffsync/adapters/sync_devices_adapters.py
> +        ):  # platform is only returned with device data if not provided on the job form/csv
Did ruff autoformat do this?  This looks wonky.

2024-10-10 14:21 UTC, jeffkala commented on nautobot_device_onboarding/diffsync/adapters/sync_devices_adapters.py
> +            )
Did ruff autoformat do this?  This looks wonky.

2024-10-11 15:16 UTC, scetron requested changes
I think this just needs to have the formatting looked at as there's also a lot of diffs that are just a format change. Additionally the format that was changed looks incorrect.

2024-10-11 19:45 UTC, scetron approved these changes

2024-10-18 21:21 UTC, merged